### ISSUE TITLE
RenderPipelineDesc::shaderStages is shared_ptr, IDevice::createShaderStages returns unique_ptr

### ISSUE THREAD

**Issue by tksuoran** [facebook/igl#106]
- `IDevice::createShaderStages()` returns `unique_pt`
- `createRenderPipeline()` wants `std::shared_ptr<IShaderStages> shaderStages` in `RenderPipelineDesc`

Please clarify how this is supposed to be used. Thanks.

**Comment by EricGriffith** [comment]
We try to use unique_ptr whenever we can because shared_ptr has more overhead. However, the same IShaderStages can be used in more than one IRenderPipelineState, so we need to hold a shared_ptr to the shader stages. You can std::move the unique_ptr into the shared_ptr on the RenderPipelineDesc or into your own shared_ptr variable and assign a copy into the descriptor.
