### ISSUE TITLE
Are there any plans to have this be compatible with Khronos's ANARI?

### ISSUE THREAD

**Issue by F35H** [facebook/igl#44]
Greetings I've personally been looking to use Khronos's Anari which sounds like this could be easily compatible with. Note, I have not looked too much into this project myself, so please correct me if I'm wrong.

https://www.khronos.org/anari

**Comment by gnolnuhc** [comment]
IGL is cross platform APIs that talks directly to GPU. It's an abstraction of various graphics APIs like OpenGL, Metal and Vulkan.

ANARI is Khronos' open standard API for rendering engines. Each ANARI implementation has its own way of handling GPUs. If you just use a specific ANARI compatible rendering engine, I don't think you need IGL because that ANARI library would handle it for you. If you are implementing your own rendering engine, you can certainly use IGL for handling GPU calls.
