### ISSUE TITLE
Can I do persistently mapped buffers?

### ISSUE THREAD

**Issue by tksuoran** [facebook/igl#51]
`IBuffer::map()` comments give the impression that `map()` is not a performant path. Are persistently mapped buffers possible? How would I use them?

Thanks!

**Comment by corporateshark** [comment]
Persistently mapped buffers are supported and are very fast. In Vulkan, the underlying buffer is always mapped persistently wherever possible. A call to `unmap()` is required to make sure that any non-coherent memory is `flushed` properly.

`map()/unmap()` will be very slow in case you try to do it on a device-local buffer in GPU memory.

**Comment by tksuoran** [comment]
It would be great if the documentation / comments were updated to mention persistently mapped buffer as valid and performant use case for `map()`:

> @brief Map a portion of the contents of a GPU Buffer into memory.

The following is not fully true, right? 
> Not efficient; intended primarily for debug and test use.

This is also not always true?
> unmap() must be called before the buffer is used again in any GPU operations.

If I have a buffer with shared resource storage mode, is that persistent and coherent, so that I can map() it once and no need to unmap()?

**Comment by corporateshark** [comment]
Yes, the update is on the way.

>If I have a buffer with shared resource storage mode, is that persistent and coherent, so that I can map() it once and no need to unmap()?

You have to `unmap()` because there's no way to know if a buffer is coherent through the IGL API (coherent in the sense of `VK_MEMORY_PROPERTY_HOST_COHERENT_BIT`). `IBuffer::unmap()` is basically a no-op on Vulkan host-visible buffers except that it will `flush` properly.

Technically, if you do not want to call `unmap()` at all, you can downcast your `IBuffer` to `igl::vulkan::Buffer` and then access `currentVulkanBuffer()->isCoherentMemory()` and call `flushMappedMemory()` manually.

**Comment by corporateshark** [comment]
`igl::vulkan::Buffer::currentVulkanBuffer()` is now `public`: 4265f2511c181bcd51e9c28d5598f6aabc78361e

**Comment by corporateshark** [comment]
Btw, using `IBuffer::upload()` on Vulkan will take advantage of persistent mapping and do `memcpy` internally.

**Comment by tksuoran** [comment]
`IBuffer::upload()` path would do `memcpy()` while I would prefer to write directly to the persistently mapped memory.

Could `IBuffer` tell if it can be persistent-coherent-mapped, then I could choose between writing directly to the memory or using `upload()`?
