### ISSUE TITLE
Why does the Android OpenGL demo flicker frequently?

### ISSUE THREAD

**Issue by vinsentli** [facebook/igl#97]
Android OpenGL demo flicker frequently，Vulkan demo is OK .

**Comment by dmannemela** [comment]
Could you provide more information? Which demo? 
Please provide the command line. you were using and also which device were you testing on?

**Comment by vinsentli** [comment]
I test Textured3DCubeSession， ColorSession , the two examples both  flicker frequently .
My device is Samsung Galaxy Tab S7+ and  Huawei Mate 60.

https://github.com/facebook/igl/assets/7352338/d1f0a776-1baf-41a5-b721-81fca3227157

**Comment by vinsentli** [comment]
https://github.com/facebook/igl/assets/7352338/8e80c312-0b66-4bbd-b314-d1ad2b3e70c8

**Comment by BattleAxeVR** [comment]
I noticed this as well.

**Comment by EricGriffith** [comment]
It's because we're always calling ICommandBuffer::present(), but EGL is doing this for us on Android. We added a shouldPresent flag to ShellParams (https://github.com/facebook/igl/blob/602c042141a31bdefdc13c6a81786d9e704bbf92/shell/shared/renderSession/ShellParams.h#L29) so we can avoid this, but we haven't updated the sample apps yet to check this before calling present.

**Comment by vinsentli** [comment]
> It's because we're always calling ICommandBuffer::present(), but EGL is doing this for us on Android. We added a shouldPresent flag to ShellParams so we can avoid this:
> 
> https://github.com/facebook/igl/blob/602c042141a31bdefdc13c6a81786d9e704bbf92/shell/shared/renderSession/ShellParams.h#L29
> 
> 
> We haven't updated the sample apps yet to check this before calling present though.

yes , it works fine now
